// <auto-generated />
using System;
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Data.Migrations
{
    [DbContext(typeof(ServiceContext))]
    [Migration("20230624092644_ChangedContactData")]
    partial class ChangedContactData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.7");

            modelBuilder.Entity("API.Entities.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("ServiceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("User")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId");

                    b.ToTable("Comment");
                });

            modelBuilder.Entity("API.Entities.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AddressCity")
                        .HasColumnType("TEXT");

                    b.Property<string>("AddressCountry")
                        .HasColumnType("TEXT");

                    b.Property<string>("AddressNumber1")
                        .HasColumnType("TEXT");

                    b.Property<string>("AddressNumber2")
                        .HasColumnType("TEXT");

                    b.Property<string>("AddressPostal")
                        .HasColumnType("TEXT");

                    b.Property<string>("AddressStreet")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("API.Entities.ContactCustom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ContactId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContactId");

                    b.ToTable("ContactCustom");
                });

            modelBuilder.Entity("API.Entities.Info", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("OpeningHoursFridayEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("OpeningHoursFridayStart")
                        .HasColumnType("TEXT");

                    b.Property<string>("OpeningHoursMondayEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("OpeningHoursMondayStart")
                        .HasColumnType("TEXT");

                    b.Property<string>("OpeningHoursSaturdayEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("OpeningHoursSaturdayStart")
                        .HasColumnType("TEXT");

                    b.Property<string>("OpeningHoursSundayEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("OpeningHoursSundayStart")
                        .HasColumnType("TEXT");

                    b.Property<string>("OpeningHoursThursdayEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("OpeningHoursThursdayStart")
                        .HasColumnType("TEXT");

                    b.Property<string>("OpeningHoursTuesdayEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("OpeningHoursTuesdayStart")
                        .HasColumnType("TEXT");

                    b.Property<string>("OpeningHoursWednesdayEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("OpeningHoursWednesdayStart")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Infos");
                });

            modelBuilder.Entity("API.Entities.InfoAnnouncement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateAndTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("InfoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("InfoId");

                    b.ToTable("InfoAnnouncement");
                });

            modelBuilder.Entity("API.Entities.PictureUrl", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ServiceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId");

                    b.ToTable("PictureUrl");
                });

            modelBuilder.Entity("API.Entities.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PlannedDateOfCompletion")
                        .HasColumnType("TEXT");

                    b.Property<int>("Price")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("API.Entities.Comment", b =>
                {
                    b.HasOne("API.Entities.Service", "Service")
                        .WithMany("Comments")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Service");
                });

            modelBuilder.Entity("API.Entities.ContactCustom", b =>
                {
                    b.HasOne("API.Entities.Contact", "Contact")
                        .WithMany("ContactCustoms")
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contact");
                });

            modelBuilder.Entity("API.Entities.InfoAnnouncement", b =>
                {
                    b.HasOne("API.Entities.Info", "Info")
                        .WithMany("InfoAnnouncements")
                        .HasForeignKey("InfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Info");
                });

            modelBuilder.Entity("API.Entities.PictureUrl", b =>
                {
                    b.HasOne("API.Entities.Service", "Service")
                        .WithMany("PictureUrls")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Service");
                });

            modelBuilder.Entity("API.Entities.Contact", b =>
                {
                    b.Navigation("ContactCustoms");
                });

            modelBuilder.Entity("API.Entities.Info", b =>
                {
                    b.Navigation("InfoAnnouncements");
                });

            modelBuilder.Entity("API.Entities.Service", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("PictureUrls");
                });
#pragma warning restore 612, 618
        }
    }
}
